{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acmerobotics.slothboard",
    "module": "dashboard",
    "version": "0.3.2+0.6.0-6165.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.slothboard",
          "module": "core",
          "version": {
            "requires": "0.3.2+0.6.0-6165.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.3.aar",
          "url": "dashboard-0.3.2+0.6.0-6165.3.aar",
          "size": 442044,
          "sha512": "920fd0213511d92b94a260641659799a0e732cb253dcb2e8317dabf01040e066483b68496c05892eeca770e4909e8b0ac7f6f69c0b25ff52618a0c6f7bfb7dce",
          "sha256": "607ac3c2b593856db057c6fd4516fdf2fb9b11646bb8fa4ff1eb2d6ddfcb9c83",
          "sha1": "a24e4f7eccd608500f7d1ae0d58c3f8023481811",
          "md5": "f8a959a38e33f588e1cf571066f850fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.frozenmilk.sinister",
          "module": "Sloth",
          "version": {
            "strictly": "0.3.2",
            "requires": "0.3.2"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "com.acmerobotics.slothboard",
          "module": "core",
          "version": {
            "requires": "0.3.2+0.6.0-6165.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.3.aar",
          "url": "dashboard-0.3.2+0.6.0-6165.3.aar",
          "size": 442044,
          "sha512": "920fd0213511d92b94a260641659799a0e732cb253dcb2e8317dabf01040e066483b68496c05892eeca770e4909e8b0ac7f6f69c0b25ff52618a0c6f7bfb7dce",
          "sha256": "607ac3c2b593856db057c6fd4516fdf2fb9b11646bb8fa4ff1eb2d6ddfcb9c83",
          "sha1": "a24e4f7eccd608500f7d1ae0d58c3f8023481811",
          "md5": "f8a959a38e33f588e1cf571066f850fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.3-sources.jar",
          "url": "dashboard-0.3.2+0.6.0-6165.3-sources.jar",
          "size": 33873,
          "sha512": "eb673cfc0f1b0259c64a42722bcd5935e42bd2f45d471ec076383e75df3852c0290c5173fe8214adbd182779c92a7b64692e497184385ce8819392ace3dd8349",
          "sha256": "090c62d212099696c5ccf6aeb1ccd812f1b3c55b46e832b3014c6dae3335e335",
          "sha1": "6555a2f6d0ad090a22681d5dbce68f4fcee1d643",
          "md5": "fc8b922065bf631145a6fc7f05ff74f8"
        }
      ]
    }
  ]
}
