{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acmerobotics.slothboard",
    "module": "dashboard",
    "version": "0.3.2+0.6.0-6165.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.slothboard",
          "module": "core",
          "version": {
            "requires": "0.3.2+0.6.0-6165.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.6.aar",
          "url": "dashboard-0.3.2+0.6.0-6165.6.aar",
          "size": 492633,
          "sha512": "30b5a85a7d9784a8b02326d4dece74ddb75d54bc5e31088a1c2731a4e467a06b45a67ffea4062e1228d3d4cfb3301e891a50fcab8f1b9ec572fcb02c9cba530d",
          "sha256": "87fc784cc6795a1ebfb3e0c243bb21a9e0a710a541bfbd7ae2e9bdb00ccc195e",
          "sha1": "171b869d4f8e933eb6af60b7fa5f69beaafd66a7",
          "md5": "ab784d22464c9cec61895624435988db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.frozenmilk.sinister",
          "module": "Sloth",
          "version": {
            "strictly": "0.3.2",
            "requires": "0.3.2"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "com.acmerobotics.slothboard",
          "module": "core",
          "version": {
            "requires": "0.3.2+0.6.0-6165.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.6.aar",
          "url": "dashboard-0.3.2+0.6.0-6165.6.aar",
          "size": 492633,
          "sha512": "30b5a85a7d9784a8b02326d4dece74ddb75d54bc5e31088a1c2731a4e467a06b45a67ffea4062e1228d3d4cfb3301e891a50fcab8f1b9ec572fcb02c9cba530d",
          "sha256": "87fc784cc6795a1ebfb3e0c243bb21a9e0a710a541bfbd7ae2e9bdb00ccc195e",
          "sha1": "171b869d4f8e933eb6af60b7fa5f69beaafd66a7",
          "md5": "ab784d22464c9cec61895624435988db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.6-sources.jar",
          "url": "dashboard-0.3.2+0.6.0-6165.6-sources.jar",
          "size": 37656,
          "sha512": "a0308b2b92c70a67e524d52276ccc2f436b8b2210be6b9015e741655668153d9a0ae352327a26e9063094984a68ca66162e6b4b0da2e7e77b77f0fc988d37b4f",
          "sha256": "b843c8b7113b62586595a342775195b5c5227b8a7accb8d15b592f604a55b609",
          "sha1": "697add1c69552fc19cd0fcffc2168a0381e9ae3e",
          "md5": "51305e52a89dd9e015c95cd33c4af470"
        }
      ]
    }
  ]
}
