"""BIOBUZZ HIVE-cell SnapScript for the Limelight 3A — pipeline 2, BLUE.

Decides, on the camera, whether one alliance's HIVE cell is scorable, and which of its two cells
(scoring side or audience side) is in view — which in turn says which half of the field the robot is
on, since each cell faces its own side. The verdict is visibility:
a cell that is up shows its AprilTag cluster to the camera, and a cell that has tipped down points
its cluster away, so it drops out of frame entirely. MIN_VISIBLE_TAGS of the alliance's eight ids in
frame means scorable; none for HOLD_SECONDS means tipped. Roll is measured and reported either way,
and REQUIRE_UPRIGHT additionally applies the manual's |roll| < 90 test — useful when a tipped
cluster stays readable rather than vanishing. Everything is baked in here, so the Control Hub sends
nothing at all — it selects this pipeline once at init and then only reads llpython.

Two pipelines, one per alliance. The manual's first targeting condition (only target clusters of
your own alliance) is structural rather than a check: this script only knows its own alliance's
eight ids, so the other alliance's tags land in `strangers` and are drawn but never considered.

ROLL. The Control Hub SDK's AprilTagDetection exposes ftcPose.roll from a full 6-DOF solve. A
SnapScript has no camera intrinsics and no tag size, so there is no pose to solve — but roll is
rotation about the camera's own viewing axis, which is exactly the tag's apparent rotation in the
image, and that comes straight from the corner order aruco already returns. c0->c1 is the tag's top
edge: it points right (roll ~0) for an upright tag and left (roll ~180) for an upside-down one.
So the number below is not the SDK's field, but it measures the same angle and the same |roll| < 90
test applies. A cluster's roll is the circular mean over its visible tags, so one badly-decoded
corner cannot flip the verdict on its own.

GENERATED by scripts/generate-limelight-pipelines.py from limelight/cell_tip_snapscript.py.
Do not edit this file — edit the template and re-run the generator.

Upload: Limelight web UI (http://limelight.local:5801) -> pick the pipeline index -> Input tab ->
pipeline type "Python" -> paste the matching limelight/pipelines/ file -> Save. The index each
alliance expects is LimelightCamera.redPipeline / .bluePipeline, and the two have to agree; a
mismatch is caught at run time by the checksum in llpython[6].

llpython (here -> hub), 8 doubles, read by LimelightCamera.parse():
    0     tipped: not scorable for HOLD_SECONDS straight, 1 or 0
    1     scorable: enough of this alliance's cluster is in frame (and upright, if gated), 1 or 0
    2     roll of the cluster in view, degrees (ROLL_NONE = 999 when neither is in view)
    3     how many of that cluster's four tags are visible
    4     which cell: 0 = scoring side, 1 = audience side, -1 = neither
    5     how many of the OTHER cluster's tags are visible
    6     checksum (sum) of this alliance's eight ids — identifies which pipeline answered
    7     frame counter, wrapping at 10000

llrobot is ignored.
"""

import math
import time

import cv2
import numpy as np

ALLIANCE = "BLUE"
PIPELINE_INDEX = 2
# Always (scoring-side cell, audience-side cell) in that order, so the cluster code in llpython[4]
# means the same thing for both alliances even though their id runs are ordered differently.
CLUSTERS = (("SCORING", (42, 43, 44, 45)), ("AUDIENCE", (38, 39, 40, 41)))

HOLD_SECONDS = 0.25
MIN_TAG_AREA_PX = 120.0
# How many of this alliance's tags have to be in frame to call a cell present at all.
MIN_VISIBLE_TAGS = 1
# Roll is always measured and reported; this decides whether it also gates the verdict. Off means
# the verdict is pure visible/not-visible, which is what a tipped cell actually looks like most of
# the time — its cluster points away and is not in frame at all, never inverted-but-readable.
REQUIRE_UPRIGHT = False
UPRIGHT_MAX_ROLL_DEG = 90.0
# Off means an empty frame reports tipped once the hold elapses, so a camera pointed at a wall reads
# the same as a tipped cell. On withholds that until the cluster has been seen at least once.
REQUIRE_SEEN = False
# Sent in place of a roll when no cluster is in view. NaN is not valid JSON, and llpython goes out
# through the Limelight's results JSON, so a bare NaN can cost the hub the whole payload.
ROLL_NONE = 999.0
DRAW_OVERLAY = True

ALL_IDS = CLUSTERS[0][1] + CLUSTERS[1][1]
CHECKSUM = float(sum(ALL_IDS))
NO_CONTOUR = np.array([[]])

FONT = cv2.FONT_HERSHEY_SIMPLEX
GREEN = (0, 255, 0)
RED = (0, 0, 255)
AMBER = (0, 190, 255)
GREY = (150, 150, 150)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)


def _make_detector():
    """Returns detect(gray) -> (corners, ids), across both the old and new cv2.aruco APIs."""
    aruco = cv2.aruco
    if hasattr(aruco, "getPredefinedDictionary"):
        dictionary = aruco.getPredefinedDictionary(aruco.DICT_APRILTAG_36h11)
    else:
        dictionary = aruco.Dictionary_get(aruco.DICT_APRILTAG_36h11)

    if hasattr(aruco, "ArucoDetector"):
        detector = aruco.ArucoDetector(dictionary, aruco.DetectorParameters())
        return lambda gray: detector.detectMarkers(gray)[:2]

    params = aruco.DetectorParameters_create()
    return lambda gray: aruco.detectMarkers(gray, dictionary, parameters=params)[:2]


_detect = _make_detector()

# Module scope, so it survives between frames — this is where the hold window lives.
_last_good = None
_seen_since_start = False
_frames = 0


def _tag_roll_deg(pts):
    """In-image rotation of one tag, from its top edge: ~0 upright, ~180 upside-down."""
    dx = pts[1][0] - pts[0][0]
    dy = pts[1][1] - pts[0][1]
    return math.degrees(math.atan2(dy, dx))


def _circular_mean_deg(angles):
    """Mean of angles that wrap, so 179 and -179 average to 180 rather than 0."""
    x = sum(math.cos(math.radians(a)) for a in angles)
    y = sum(math.sin(math.radians(a)) for a in angles)
    if x == 0.0 and y == 0.0:
        return float("nan")
    return math.degrees(math.atan2(y, x))


def _label(image, text, origin, color, scale=0.5, thickness=1):
    """Text on a filled black plate, so it stays readable over a bright field."""
    (w, h), base = cv2.getTextSize(text, FONT, scale, thickness)
    x, y = origin
    cv2.rectangle(image, (x - 2, y - h - 2), (x + w + 2, y + base), BLACK, -1)
    cv2.putText(image, text, (x, y), FONT, scale, color, thickness, cv2.LINE_AA)


def _draw_overlay(image, found_by_cluster, strangers, rolls, target, tipped, scorable):
    """Everything the hub knows, drawn on the frame the Limelight web UI streams."""
    for pts, tag_id in strangers:
        cv2.polylines(image, [pts.astype(np.int32)], True, GREY, 1)
        cx, cy = pts.mean(axis=0)
        _label(image, "%d" % tag_id, (int(cx) - 10, int(cy)), GREY)

    for c, tags in enumerate(found_by_cluster):
        upright = not math.isnan(rolls[c]) and abs(rolls[c]) < UPRIGHT_MAX_ROLL_DEG
        color = GREEN if upright or not REQUIRE_UPRIGHT else RED
        for pts, tag_id in tags:
            cv2.polylines(image, [pts.astype(np.int32)], True, color, 2)
            cx, cy = pts.mean(axis=0)
            _label(image, "%d" % tag_id, (int(cx) - 10, int(cy)), color)

    y = 18
    _label(image, "%s  pipeline %d" % (ALLIANCE, PIPELINE_INDEX), (8, y), WHITE)

    for c, (label, ids) in enumerate(CLUSTERS):
        y += 20
        tags = found_by_cluster[c]
        roll = rolls[c]
        if not tags:
            _label(image, "%-8s %d-%d  0/4  --" % (label, ids[0], ids[-1]), (8, y), GREY)
            continue
        upright = not math.isnan(roll) and abs(roll) < UPRIGHT_MAX_ROLL_DEG
        _label(image, "%-8s %d-%d  %d/4  roll %+.1f  %s%s"
               % (label, ids[0], ids[-1], len(tags), roll,
                  "UP" if upright else "DOWN", "  <-- target" if c == target else ""),
               (8, y), GREEN if upright else RED)

    y += 8
    if tipped:
        (w, h), _ = cv2.getTextSize("TIPPED", FONT, 1.1, 3)
        cv2.rectangle(image, (4, y + 8), (12 + w, y + 20 + h), RED, -1)
        cv2.putText(image, "TIPPED", (8, y + 14 + h), FONT, 1.1, WHITE, 3, cv2.LINE_AA)
        y += 28 + h
    elif scorable:
        (w, h), _ = cv2.getTextSize("SCORABLE", FONT, 1.1, 3)
        cv2.rectangle(image, (4, y + 8), (12 + w, y + 20 + h), GREEN, -1)
        cv2.putText(image, "SCORABLE", (8, y + 14 + h), FONT, 1.1, BLACK, 3, cv2.LINE_AA)
        y += 28 + h
    else:
        y += 20
        _label(image, "NOT SCORABLE, waiting out the hold", (8, y), AMBER, 0.6, 2)

    y += 20
    away = 0.0 if _last_good is None else time.monotonic() - _last_good
    _label(image, "not scorable for %.2fs / %.2fs   need %d tag%s%s   seen %s   frame %d"
           % (away, HOLD_SECONDS, MIN_VISIBLE_TAGS, "" if MIN_VISIBLE_TAGS == 1 else "s",
              " + |roll| < %.0f" % UPRIGHT_MAX_ROLL_DEG if REQUIRE_UPRIGHT else "",
              "yes" if _seen_since_start else "no", _frames), (8, y), WHITE, 0.45)


def runPipeline(image, llrobot):
    global _last_good, _seen_since_start, _frames

    now = time.monotonic()
    _frames = (_frames + 1) % 10000

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if image.ndim == 3 else image
    corners, found = _detect(gray)

    found_by_cluster = [[], []]
    strangers = []

    if found is not None and len(found) > 0:
        for quad, tag_id in zip(corners, found.flatten()):
            pts = quad.reshape(-1, 2).astype(np.float32)
            if abs(cv2.contourArea(pts)) < MIN_TAG_AREA_PX:
                continue
            tag_id = int(tag_id)
            for c, (_, ids) in enumerate(CLUSTERS):
                if tag_id in ids:
                    found_by_cluster[c].append((pts, tag_id))
                    break
            else:
                strangers.append((pts, tag_id))

    rolls = [_circular_mean_deg([_tag_roll_deg(pts) for pts, _ in tags]) if tags else float("nan")
             for tags in found_by_cluster]

    # The cluster in view is the one with more tags; an upright one wins a tie, since an upright
    # cluster is the one the robot can act on.
    target = -1
    best = (-1, -1)  # (upright, visible count)
    for c, tags in enumerate(found_by_cluster):
        if not tags:
            continue
        upright = 1 if (not math.isnan(rolls[c]) and abs(rolls[c]) < UPRIGHT_MAX_ROLL_DEG) else 0
        if (upright, len(tags)) > best:
            best = (upright, len(tags))
            target = c

    if target < 0:
        roll = float("nan")
        visible = 0
        other_visible = 0
    else:
        roll = rolls[target]
        visible = len(found_by_cluster[target])
        other_visible = len(found_by_cluster[1 - target])

    # One timer covers both criteria: the cell is "good" when enough of its cluster is in frame and,
    # if REQUIRE_UPRIGHT is on, reading right-side up. Long enough not-good means tipped.
    upright_ok = not REQUIRE_UPRIGHT or (target >= 0 and abs(roll) < UPRIGHT_MAX_ROLL_DEG)
    scorable = visible >= MIN_VISIBLE_TAGS and upright_ok
    if scorable:
        _last_good = now
        _seen_since_start = True
    elif _last_good is None:
        _last_good = now

    away_s = now - _last_good
    tipped = not scorable and away_s >= HOLD_SECONDS and (_seen_since_start or not REQUIRE_SEEN)

    if DRAW_OVERLAY:
        _draw_overlay(image, found_by_cluster, strangers, rolls, target, tipped, scorable)

    llpython = [
        1.0 if tipped else 0.0,
        1.0 if scorable else 0.0,
        ROLL_NONE if math.isnan(roll) else float(roll),
        float(visible),
        float(target),
        float(other_visible),
        CHECKSUM,
        float(_frames),
    ]

    # A contour is returned only so tx/ty/ta and result.isValid() track the targeted cluster when
    # one is in view; the verdict itself rides entirely in llpython.
    if target < 0:
        return NO_CONTOUR, image, llpython
    biggest = max(found_by_cluster[target], key=lambda t: abs(cv2.contourArea(t[0])))[0]
    return biggest.reshape(-1, 1, 2).astype(np.int32), image, llpython
