"""BIOBUZZ cell-tip SnapScript for the Limelight 3A — pipeline 2, BLUE_1.

Watches the four AprilTags under one cell and decides, on the camera, whether that cell has tipped
over onto them: the verdict is false while any of the four is in view and true once all four have
been out of view continuously for HOLD_SECONDS. Everything is baked in here, so the Control Hub
sends nothing at all — it selects this pipeline once at init and then only reads llpython.

GENERATED by scripts/generate-limelight-pipelines.py from limelight/cell_tip_snapscript.py.
Do not edit this file — edit the template and re-run the generator.

Upload: Limelight web UI (http://limelight.local:5801) -> pick the pipeline index -> Input tab ->
pipeline type "Python" -> paste the matching limelight/pipelines/ file -> Save. The index each cell
expects is Context.Cell's `pipeline` field, and the two have to agree; a mismatch is caught at run
time by the checksum in llpython[5], which the hub checks against the cell it thinks it selected.

llpython (here -> hub), 8 doubles, read by LimelightCamera.parse():
    0     tipped, 1 or 0
    1     how many of the four are visible this frame
    2     visible bitmask, bit i = TAG_IDS[i]
    3     seconds since any of the four was last seen
    4     whether any of them has been seen since the pipeline started
    5     checksum (sum) of TAG_IDS — identifies which cell this pipeline answers about
    6     AprilTags of any id in this frame
    7     frame counter, wrapping at 10000

llrobot is ignored.
"""

import time

import cv2
import numpy as np

TAG_IDS = (38, 39, 40, 41)  # BLUE_1, Limelight pipeline 2

HOLD_SECONDS = 0.25
MIN_TAG_AREA_PX = 120.0
REQUIRE_SEEN = False
DRAW_OVERLAY = True

CHECKSUM = float(sum(TAG_IDS))
NO_CONTOUR = np.array([[]])


def _make_detector():
    """Returns detect(gray) -> (corners, ids), across both the old and new cv2.aruco APIs."""
    aruco = cv2.aruco
    if hasattr(aruco, "getPredefinedDictionary"):
        dictionary = aruco.getPredefinedDictionary(aruco.DICT_APRILTAG_36h11)
    else:
        dictionary = aruco.Dictionary_get(aruco.DICT_APRILTAG_36h11)

    if hasattr(aruco, "ArucoDetector"):
        detector = aruco.ArucoDetector(dictionary, aruco.DetectorParameters())
        return lambda gray: detector.detectMarkers(gray)[:2]

    params = aruco.DetectorParameters_create()
    return lambda gray: aruco.detectMarkers(gray, dictionary, parameters=params)[:2]


_detect = _make_detector()

# Module scope, so it survives between frames — this is where the hold window lives.
_last_seen = None
_seen_since_start = False
_frames = 0


def runPipeline(image, llrobot):
    global _last_seen, _seen_since_start, _frames

    now = time.monotonic()
    _frames = (_frames + 1) % 10000
    if _last_seen is None:
        _last_seen = now

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if image.ndim == 3 else image
    corners, found = _detect(gray)

    mask = 0
    visible = 0
    detected = 0
    best_quad = None
    best_area = 0.0

    if found is not None and len(found) > 0:
        for quad, tag_id in zip(corners, found.flatten()):
            pts = quad.reshape(-1, 2).astype(np.float32)
            area = abs(cv2.contourArea(pts))
            if area < MIN_TAG_AREA_PX:
                continue
            detected += 1
            tag_id = int(tag_id)
            for i, wanted in enumerate(TAG_IDS):
                if tag_id != wanted or (mask >> i) & 1:
                    continue
                mask |= 1 << i
                visible += 1
                if area > best_area:
                    best_area = area
                    best_quad = pts
                break

    if visible > 0:
        _last_seen = now
        _seen_since_start = True

    hidden_s = now - _last_seen
    tipped = visible == 0 and hidden_s >= HOLD_SECONDS and (_seen_since_start or not REQUIRE_SEEN)

    if DRAW_OVERLAY:
        if best_quad is not None:
            cv2.polylines(image, [best_quad.astype(np.int32)], True, (0, 255, 0), 2)
        cv2.putText(
            image,
            "TIPPED" if tipped else "%d/4 visible  %.2fs" % (visible, hidden_s),
            (8, 24),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (0, 0, 255) if tipped else (0, 255, 0),
            2,
        )

    llpython = [
        1.0 if tipped else 0.0,
        float(visible),
        float(mask),
        float(hidden_s),
        1.0 if _seen_since_start else 0.0,
        CHECKSUM,
        float(detected),
        float(_frames),
    ]

    # A contour is returned only so tx/ty/ta and result.isValid() track a watched tag when one is in
    # view; the tip verdict itself rides entirely in llpython.
    contour = NO_CONTOUR if best_quad is None else best_quad.reshape(-1, 1, 2).astype(np.int32)
    return contour, image, llpython
