{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acmerobotics.slothboard",
    "module": "dashboard",
    "version": "0.3.2+0.6.0-6165.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.slothboard",
          "module": "core",
          "version": {
            "requires": "0.3.2+0.6.0-6165.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.5.aar",
          "url": "dashboard-0.3.2+0.6.0-6165.5.aar",
          "size": 491910,
          "sha512": "be5164661498c62921c9651c64d2b783ea24ce8638aebd8d34c74e047194f04e7edebb5093c426509e5bdeb34f446cfa211cb1c0597c5f44fc270165f60433bc",
          "sha256": "cfd521495083b5c56ade35041bb80c4ad4f96a443fcd08c6d8c653692fa6ee3b",
          "sha1": "261854f25c933e8cd642c96d34844e5a6aa404ed",
          "md5": "11df27a52965c6a9960892f4c19dd5f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.frozenmilk.sinister",
          "module": "Sloth",
          "version": {
            "strictly": "0.3.2",
            "requires": "0.3.2"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "com.acmerobotics.slothboard",
          "module": "core",
          "version": {
            "requires": "0.3.2+0.6.0-6165.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.5.aar",
          "url": "dashboard-0.3.2+0.6.0-6165.5.aar",
          "size": 491910,
          "sha512": "be5164661498c62921c9651c64d2b783ea24ce8638aebd8d34c74e047194f04e7edebb5093c426509e5bdeb34f446cfa211cb1c0597c5f44fc270165f60433bc",
          "sha256": "cfd521495083b5c56ade35041bb80c4ad4f96a443fcd08c6d8c653692fa6ee3b",
          "sha1": "261854f25c933e8cd642c96d34844e5a6aa404ed",
          "md5": "11df27a52965c6a9960892f4c19dd5f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.5-sources.jar",
          "url": "dashboard-0.3.2+0.6.0-6165.5-sources.jar",
          "size": 37095,
          "sha512": "1ae0f7f39385ed55a2e806717afba4a931417d5a96a30ae9309ebf5bfa87ed29f17c32d6190798b88cd2dc7ee38908aeb219833925f4818251c51deba7a36e31",
          "sha256": "61d487b75f88cc4a999153d4016df3b1535ed3b6b79f0a3c2b997ed48d9661ca",
          "sha1": "17f1d0dd1639f69b0f488c64fe77db5d0eb5509f",
          "md5": "78b6115e529d2088fa12c5c7e63c73ec"
        }
      ]
    }
  ]
}
