{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acmerobotics.slothboard",
    "module": "dashboard",
    "version": "0.3.2+0.6.0-6165.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.slothboard",
          "module": "core",
          "version": {
            "requires": "0.3.2+0.6.0-6165.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.4.aar",
          "url": "dashboard-0.3.2+0.6.0-6165.4.aar",
          "size": 490162,
          "sha512": "a21a2e743c17db39ea32fc18e204bf502c3059478ccf1c9163770a0b79c35fed0384cbb142063c2b5b0ad53c6ece9d6df430e2a52ea4bd3782eacb8988dc9fc0",
          "sha256": "5898b2aaf98f3da94d605f7762ede140b92a2ac8807b0a171ae94bf1a834bb50",
          "sha1": "5b45d4ad3ee86201e1dfc125f4a3ffce2280eb09",
          "md5": "b4e3313b142467d24fd3df531cb4a2b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.frozenmilk.sinister",
          "module": "Sloth",
          "version": {
            "strictly": "0.3.2",
            "requires": "0.3.2"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "com.acmerobotics.slothboard",
          "module": "core",
          "version": {
            "requires": "0.3.2+0.6.0-6165.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.4.aar",
          "url": "dashboard-0.3.2+0.6.0-6165.4.aar",
          "size": 490162,
          "sha512": "a21a2e743c17db39ea32fc18e204bf502c3059478ccf1c9163770a0b79c35fed0384cbb142063c2b5b0ad53c6ece9d6df430e2a52ea4bd3782eacb8988dc9fc0",
          "sha256": "5898b2aaf98f3da94d605f7762ede140b92a2ac8807b0a171ae94bf1a834bb50",
          "sha1": "5b45d4ad3ee86201e1dfc125f4a3ffce2280eb09",
          "md5": "b4e3313b142467d24fd3df531cb4a2b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dashboard-0.3.2+0.6.0-6165.4-sources.jar",
          "url": "dashboard-0.3.2+0.6.0-6165.4-sources.jar",
          "size": 35771,
          "sha512": "050340b70b10989e43629d30c9a2e51df33baf1548bcc594f5e59c1076fd8c2c5365d84fab11330c9d5da07c22ec9a736c378a040e2ff332fa744f59d29ea90e",
          "sha256": "60b5bbbaaa66ed5fd74b58a25b9618f8bb8ed6da47b93f91c01ff2198808cc86",
          "sha1": "2307f38fffe0dd0070318c7521e6d9970aa2a3aa",
          "md5": "6ed4a13ccaf6e4fb515810f74f84c6ed"
        }
      ]
    }
  ]
}
