{
  "formatVersion": "1.1",
  "component": {
    "group": "com.acmerobotics.slothboard",
    "module": "core",
    "version": "0.3.2+0.6.0-6165.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-0.3.2+0.6.0-6165.5.jar",
          "url": "core-0.3.2+0.6.0-6165.5.jar",
          "size": 73454,
          "sha512": "a16469c9a89dda916efb73ec46fe203b660a82fbe6f1554e7d8f1716c3390cd2ece356051b66efc198c6257da6f642b1569e8b4dd7e8d7716852696faa6ba6fd",
          "sha256": "8696e124c8bfb3608be8e098b745ad44e2e2b80f97e26f3a3c7ae7b06e533717",
          "sha1": "d52584fb9c5c83b8a169448fed646863f243f590",
          "md5": "3045a0c8ab44672c0b20358b80593485"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.3.2+0.6.0-6165.5.jar",
          "url": "core-0.3.2+0.6.0-6165.5.jar",
          "size": 73454,
          "sha512": "a16469c9a89dda916efb73ec46fe203b660a82fbe6f1554e7d8f1716c3390cd2ece356051b66efc198c6257da6f642b1569e8b4dd7e8d7716852696faa6ba6fd",
          "sha256": "8696e124c8bfb3608be8e098b745ad44e2e2b80f97e26f3a3c7ae7b06e533717",
          "sha1": "d52584fb9c5c83b8a169448fed646863f243f590",
          "md5": "3045a0c8ab44672c0b20358b80593485"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.3.2+0.6.0-6165.5-sources.jar",
          "url": "core-0.3.2+0.6.0-6165.5-sources.jar",
          "size": 38863,
          "sha512": "b8b7dad35489ad7e8fb634c162c075724eb54b139061a258b6e5b0f26725031294714d80cf9072f5487d51e0be26110789c85f289c07a5e5163ad8a86e0362c6",
          "sha256": "d9f02bd1853ccc44354bb230f2acae70241580405f67976e1554d49a934241cf",
          "sha1": "7c4c8e7837dd7f6f89c16c87b6e100f02938e8b0",
          "md5": "98b37a2d912de3553594608fc1950b0c"
        }
      ]
    }
  ]
}
