#!/usr/bin/env python3
"""Stamps limelight/cell_tip_snapscript.py out once per alliance into limelight/pipelines/.

The alliances, their pipeline indices and their tag ids are parsed straight out of
LimelightCamera.java rather than kept as a second copy, so the scripts and the hub cannot drift.
Run this after editing the template, then re-upload both files to the matching pipeline indices.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "limelight" / "cell_tip_snapscript.py"
OUT_DIR = ROOT / "limelight" / "pipelines"
MODULE = ROOT / "TeamCode/src/main/java/org/firstinspires/ftc/teamcode/modules/LimelightCamera.java"

PIPELINE_RE = r"public static int %sPipeline = (\d+);"
IDS_RE = r"private static final int\[\] %s_%s_IDS = \{([0-9, ]+)\};"

ALLIANCE_RE = re.compile(r"^ALLIANCE = .*$", re.M)
INDEX_RE = re.compile(r"^PIPELINE_INDEX = .*$", re.M)
CLUSTERS_RE = re.compile(r"^CLUSTERS = .*$", re.M)


def alliances():
    """(ALLIANCE, pipeline index, ((\"SCORING\", ids), (\"AUDIENCE\", ids))) straight out of the module.

    Scoring first for both alliances, so llpython's cluster code means the same thing either way —
    the id runs themselves are not in the same order per alliance.
    """
    java = MODULE.read_text()
    out = []
    for name in ("red", "blue"):
        pipeline = re.search(PIPELINE_RE % name, java)
        if not pipeline:
            sys.exit("Could not find %sPipeline in %s" % (name, MODULE))
        clusters = []
        for side in ("SCORING", "AUDIENCE"):
            found = re.search(IDS_RE % (name.upper(), side), java)
            if not found:
                sys.exit("Could not find %s_%s_IDS in %s" % (name.upper(), side, MODULE))
            ids = tuple(int(t) for t in found.group(1).split(","))
            if len(ids) != 4:
                sys.exit("%s_%s_IDS should have 4 ids, found %d" % (name.upper(), side, len(ids)))
            clusters.append((side, ids))
        out.append((name.upper(), int(pipeline.group(1)), tuple(clusters)))
    return out


def main():
    template = TEMPLATE.read_text()
    for label, pattern in (("ALLIANCE", ALLIANCE_RE), ("PIPELINE_INDEX", INDEX_RE),
                           ("CLUSTERS", CLUSTERS_RE)):
        if not pattern.search(template):
            sys.exit("No %s line to replace in %s" % (label, TEMPLATE))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("pipeline*.py"):
        stale.unlink()

    for name, pipeline, clusters in alliances():
        body = ALLIANCE_RE.sub('ALLIANCE = "%s"' % name, template, count=1)
        body = INDEX_RE.sub("PIPELINE_INDEX = %d" % pipeline, body, count=1)
        body = CLUSTERS_RE.sub(
            "CLUSTERS = (%s)" % ", ".join('("%s", %s)' % (side, ids) for side, ids in clusters),
            body, count=1)
        body = body.replace("— template.\n", "— pipeline %d, %s.\n" % (pipeline, name), 1)
        body = body.replace(
            "This file is the source of truth. It is NOT what gets uploaded: `scripts/generate-limelight-\n"
            "pipelines.py` stamps it out once per alliance into limelight/pipelines/, each copy differing only in\n"
            "the alliance block. Edit this file, re-run the generator, re-upload both.",
            "GENERATED by scripts/generate-limelight-pipelines.py from limelight/cell_tip_snapscript.py.\n"
            "Do not edit this file — edit the template and re-run the generator.",
            1)
        out = OUT_DIR / ("pipeline%d_%s.py" % (pipeline, name.lower()))
        out.write_text(body)
        print("wrote %s  %s" % (out.relative_to(ROOT),
                                 "  ".join("%s %d-%d" % (s, i[0], i[-1]) for s, i in clusters)))


if __name__ == "__main__":
    main()
