#!/usr/bin/env python3
"""Stamps limelight/cell_tip_snapscript.py out once per cell into limelight/pipelines/.

The cells and their pipeline indices mirror Context.Cell; this script parses them straight out of
Context.java rather than keeping a second copy, so the two cannot drift. Run it after editing the
template, then re-upload the four files to the matching Limelight pipeline indices.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "limelight" / "cell_tip_snapscript.py"
OUT_DIR = ROOT / "limelight" / "pipelines"
CONTEXT = ROOT / "TeamCode/src/main/java/org/firstinspires/ftc/teamcode/architecture/core/Context.java"

CELL_RE = re.compile(r"^\s*([A-Z][A-Z0-9_]*)\((\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\)", re.M)
TAG_IDS_RE = re.compile(r"^TAG_IDS = \([^)]*\).*$", re.M)
CELL_NAME_RE = re.compile(r"^CELL_NAME = .*$", re.M)
PIPELINE_RE = re.compile(r"^PIPELINE_INDEX = .*$", re.M)


def cells():
    found = CELL_RE.findall(CONTEXT.read_text())
    if not found:
        sys.exit("No Cell constants found in %s" % CONTEXT)
    return [(name, int(pipeline), tuple(int(t) for t in tags))
            for name, pipeline, *tags in found]


def main():
    template = TEMPLATE.read_text()
    for name, pattern in (("TAG_IDS", TAG_IDS_RE), ("CELL_NAME", CELL_NAME_RE),
                          ("PIPELINE_INDEX", PIPELINE_RE)):
        if not pattern.search(template):
            sys.exit("No %s line to replace in %s" % (name, TEMPLATE))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("pipeline*.py"):
        stale.unlink()

    for name, pipeline, tags in cells():
        body = TAG_IDS_RE.sub(
            "TAG_IDS = (%s)" % ", ".join(str(t) for t in tags), template, count=1)
        body = CELL_NAME_RE.sub('CELL_NAME = "%s"' % name, body, count=1)
        body = PIPELINE_RE.sub("PIPELINE_INDEX = %d" % pipeline, body, count=1)
        body = body.replace("— template.\n", "— pipeline %d, %s.\n" % (pipeline, name), 1)
        body = body.replace(
            "This file is the source of truth. It is NOT what gets uploaded: `scripts/generate-limelight-\n"
            "pipelines.py` stamps it out once per cell into limelight/pipelines/, each copy differing only in\n"
            "TAG_IDS. Edit this file, re-run the generator, re-upload the four.",
            "GENERATED by scripts/generate-limelight-pipelines.py from limelight/cell_tip_snapscript.py.\n"
            "Do not edit this file — edit the template and re-run the generator.",
            1)
        out = OUT_DIR / ("pipeline%d_%s.py" % (pipeline, name.lower()))
        out.write_text(body)
        print("wrote %s  tags %s" % (out.relative_to(ROOT), list(tags)))


if __name__ == "__main__":
    main()
